---
name: pre-commit
on:
  workflow_run:
    workflows:
      - terraform-module-release
    types:
      - completed

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run pre-commit checks
        uses: saritasa-nest/saritasa-github-actions/.github/actions/pre-commit@v3.4
        with:
          ignore-commit-authors: github-actions
          node-version: '20'
          python-version: '3.x'
          tools-list: |
            terraform-docs=https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
