---
name: Update usage.tf after tag

on:
  push:
    tags: 
      - '**'

jobs:
  update-usage:
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/') && github.actor == 'github-actions'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract tag info
        id: tag_info
        run: |
          full_tag="${GITHUB_REF#refs/tags/}"
          module_path="${full_tag%/*}"

          echo "full_tag=$full_tag" >> $GITHUB_ENV
          echo "module_path=$module_path" >> $GITHUB_ENV

      - name: Update usage.tf for the tagged module
        run: |
          git checkout "${{ env.full_tag }}"
          usage_file="examples/usage.tf"

          echo "Updating usage.tf for tag ${{ env.full_tag }}"
          sed -Ei "s|(source = \"git[^?]+\?ref=).*|\1${{ env.full_tag }}\"|g" "$usage_file"
          git add "$usage_file"
          git commit -m "Update usage.tf with tag ${{ env.full_tag }}"
          
          # Force-update the tag
          git tag -f "${{ env.full_tag }}"
          git push --force origin "${{ env.full_tag }}"

      - name: Update usage.tf in main branch
        run: |
          git checkout main
          git pull origin main

          usage_file="${{ env.module_path }}/examples/usage.tf"
          echo "Updating usage.tf in main branch with tag ${{ env.full_tag }}"
          sed -Ei "s|(source = \"git[^?]+\?ref=).*|\1${{ env.full_tag }}\"|g" "$usage_file"
          git add "$usage_file"
          git commit -m "Update usage.tf in main with tag ${{ env.full_tag }}"
          git push origin main
